// <auto-generated />
namespace WebPresentation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedJobTask : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedJobTask));
        
        string IMigrationMetadata.Id
        {
            get { return "201805091851403_Added JobTask"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
